version: "3"

services:
  mongodb:
    image: mongo:latest
    networks:
      - internal


  api:
    build:
      context: .
    depends_on:
      - "mongodb"
    volumes:
      - "./.env:/app/.env"
    networks:
      - internal
    ports:
      - "3000:3000"

networks:
  internal:
    external: false
